config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "pages#profile"
  resources :trips, only: %i[show index new create] do
    resources :lodgings, only: %i[new create]
    resources :transits, only: %i[new create]
    resources :rentals, only: %i[new create]
    resources :places, only: %i[new create]
    resources :expenses, only: %i[index new create]
    resources :items, only: %i[index new create]

    member do
      get :map
      get :details
      get :overview
      get :itinerary
      get :budget
    end
  end
  resources :expenses, only: %i[edit update delete]
  resources :lodgings, only: %i[edit update delete]
  resources :transits, only: %i[edit update delete]
  resources :rentals, only: %i[edit update delete]
  resources :items, only: %i[edit update delete] do
    member do
      get :toggle_packed
    end
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :trip_users, dependent: :destroy
  has_many :users, through: :trip_users
  has_many :lodgings, dependent: :destroy
  has_many :places, dependent: :destroy
  has_many :rentals, dependent: :destroy
  has_many :transits, dependent: :destroy
  has_many :expenses, dependent: :destroy
  has_many :items, dependent: :destroy
  has_one_attached :photo

  def budget
    expenses.sum(:price_cents)
  end

  def share
    budget / users.count
  end

  def balance
    query = "SELECT users.username, SUM(expenses.price_cents) FROM expenses
    INNER JOIN users ON expenses.user_id = users.id
    WHERE expenses.trip_id = #{id}
    group by 1"
    ActiveRecord::Base.connection.exec_query(query, "SQL").to_a
  end

  def expenses_by(user)
    expenses.where(user:)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[show map details overview itinerary budget]
  def index
    @trips = current_user.future_and_current_trips.order(start_date: :desc)
  end

  def map
    @lodging_markers = markers(@trip.lodgings)
    @rental_markers = markers(@trip.rentals)
    @place_markers = markers(@trip.places)
  end

  def itinerary
    @days = @trip.start_date.to_datetime..@trip.end_date.to_datetime
    @days_with_bookings = @days.map do |day|
      lodging = @trip.lodgings.where("? between start_time AND end_time", day).first
      rental = @trip.rentals.where("? between start_time AND end_time", day).first
      transits = @trip.transits.where("start_time between ? AND ?", day, day + 1.day)
      places = @trip.places.where("date = ?", day)
      { day:, lodging:, rental:, transits:, places: }
    end
  end

  private

  def set_trip
    @trip = Trip.includes(:lodgings, :rentals, :places, :expenses, trip_users: [:user]).find(params[:id])
  end

  def markers(things)
    things.geocoded.map do |thing|
      {
        lat: thing.latitude,
        lng: thing.longitude
      }
    end
  end
end

app/views/trips/_lodgings.html.erb
<section class="lodging-section mb-4">
  <%= turbo_frame_tag "lodgings_turbo_frame" do %>

    <div class="d-flex justify-content-between align-items-start">
      <h2 class="mb-3 text-blue">Accomodations</h3>
      <%= link_to new_trip_lodging_path(trip) do  %>
        <span class="text-yellow fs-4"><i class="fa-solid fa-plus"></i></span>
      <% end %>
    </div>
    <% if trip.lodgings.empty? %>
      <%= render "lodgings/new", trip: trip, lodging: Lodging.new %>
    <% else %>
      <ul class="lodging-list">
        <% trip.lodgings.each do |lodging| %>
          <li class="bg-gray lodging">
            <h3 class="text-blue fw-bolder"><%= lodging.name %></h3>
            <div class="d-flex justify-content-between align-items-end">
              <div>
                <p class="text-small mb-1"><%= lodging.address %></p>
                <p class="mb-0"><%= lodging.start_time.strftime("%a, %d %b") %> - <%= lodging.end_time.strftime("%a, %d %b") %></p>
              </div>
              <p class="mb-0"><i class="fa-solid fa-circle-chevron-down"></i></p>
            </div>

          </li>
        <% end %>
      </ul>
    <% end %>


  <% end %>

</section>

app/views/trips/_show_banner.html.erb
<div class="show-banner">
  <div class="show-banner-image-container position-relative">
    <%= link_to trips_path, class: "back-link position-absolute" do %>
      <i class="fa-solid fa-house text-yellow"></i>
    <% end %>
    <%= cl_image_tag trip.photo.key, class: "show-banner-image" %>
    <div class="show-banner-trip-infos">
      <h1><%= trip.name %></h1>
      <div class="show-banner-trip-infos-details">
        <p class="text-gray mb-0"><span class="me-3"><i class="fa-solid fa-calendar-days text-yellow mr-3"></i></span><%= trip.start_date.strftime("%d/%-m") %> - <%= trip.end_date.strftime("%d/%-m") %></p>
        <div class="show-banner-trip-infos-details-actions">
          <div class="show-banner-trip-users me-3">
            <% trip.users.each do |user| %>
              <%= cl_image_tag user.photo.key, class: "avatar avatar-bordered" %>
            <% end %>
          </div>
          <div class="show-banner-button-actions text-yellow"><i class="fa-solid fa-ellipsis"></i></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trips/budget.html.erb
<%= turbo_frame_tag :items do %>
  <div class="budget_banner">
    <h1><%= @trip.budget %> €</h1>
    <%= raise %>
    <% @trip.balance.each do |contribution| %>
      <div class="d-flex justify-content-center">
        <p><%= contribution["username"] %></p>
        <p><%= contribution["sum"] %> €</p>
      </div>
    <% end %>
  </div>

  <ul>
    <% @expenses.each do |exp| %>
      <%= turbo_frame_tag "expense_#{exp.id}"  do %>
        <li>
          <%= link_to edit_expense_path(exp) do  %>
            <div class="d-flex justify-content-center">
              <div class="expense-left">
                <%= exp.category %>
                <p class="text-small mb-1"><%= exp.date.strftime("%d %b")  %></p>
              </div>
              <div class="expense-right">
                <p><%= exp.price_cents %>€</p>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/trips/details.html.erb
<%= turbo_frame_tag "show_content" do %>
  <%= render "show_banner", trip: @trip %>

  <div class="show_tabs sticky-top" data-controller="tabs">
    <ul class="nav nav-tabs container pt-4" id="tripShow" role="tablist">
      <li class="nav-item" role="presentation">
        <%= link_to "Overview", overview_trip_path(@trip), class: "#{'active' if params[:frame] == '' } nav-link",
                    data: { turbo_frame: :items, tabs_target: "tab", action: "click->tabs#toggle" } %>
      </li>
      <li class="nav-item" role="presentation">
        <%= link_to "Itinerary", itinerary_trip_path(@trip), class: "#{'active' if params[:frame] == 'itinerary' }nav-link",
                    data: { turbo_frame: :items, tabs_target: "tab", action: "click->tabs#toggle" } %>
      </li>
      <li class="nav-item" role="presentation">
        <%= link_to "Expenses", trip_expenses_path(@trip), class: "#{'active' if params[:frame] == 'expenses' } nav-link",
                    data: { turbo_frame: :items, tabs_target: "tab", action: "click->tabs#toggle" } %>
      </li>
      <li class="nav-item" role="presentation">
        <%= link_to "List", trip_items_path(@trip), class: "#{'active' if params[:frame] == 'list' } nav-link",
                    data: { turbo_frame: :items, tabs_target: "tab", action: "click->tabs#toggle" } %>
      </li>
    </ul>
  </div>
  <%= turbo_frame_tag :items, src: overview_trip_path(@trip) do %>
    <p>Loading...</p>
  <% end %>
<% end %>

app/views/trips/index.html.erb
<div class="container pt-5">
  <h1 class="text-blue" ><%= current_user.username.capitalize %>,
    <% if current_user.next_trip %>
      <span style = "display: block;">your next trip is in <%= current_user.next_trip_in %> days.</span>
    <% end %>
    <% if current_user.current_trip %>
      <span style = "display: block;">how is <%= current_user.current_trip.name  %>?</span>
    <% end %>
  </h1>

  <ul class="mt-4">
    <% @trips.each do |trip| %>
      <%= link_to trip_path(trip)  do %>
        <li class="mb-4">
          <div class="card-trip">
            <%= cl_image_tag trip.photo.key %>
            <div class="card-trip-infos">
              <h2><%= trip.name %></h2>
              <p><%= trip.start_date.strftime("%d %b") %> - <%= trip.end_date.strftime("%d %b") %> <%= trip.end_date.strftime("%Y") %></p>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/trips/itinerary.html.erb
<%= turbo_frame_tag :items do %>
  <div class="day-list d-flex overflow-scroll py-3 sticky">
    <% @days.each do |day| %>
      <div class="day">
      <%= link_to day.strftime("%a %d/%m"), "##{day.strftime("%d-%m")}", data: {controller: "scroll-to",   scroll_to_offset_value: "150"
} %>
      </div>
    <% end %>
  </div>
  <ul class="itinerary-days">
    <% @days_with_bookings.each do |hash_day| %>
      <li class="bg-white mb-4 py-4" id="<%= hash_day[:day].strftime("%d-%m") %>" >
        <div class="container px-4">
          <h2 class="fw-bold mb-4"><%= hash_day[:day].strftime("%a %d/%m") %></h2>
            <% if hash_day[:lodging] %>
              <div class="bg-blue ps-2 py-1 radius-8 mb-2">
                <p class="text-white mb-0"><%= hash_day[:lodging].name %></p>
              </div>
            <% end %>
            <% if hash_day[:transits] %>
              <% hash_day[:transits].each do |transit| %>
                <div class="bg-yellow ps-2 py-1 radius-8 mb-2">
                  <p class="text-blue mb-0"><%= transit.from %> <%= transit.start_time.strftime("%H:%M") %> - <%= transit.to %> <%= transit.end_time.strftime("%H:%M") %></p>
                </div>
              <% end %>
            <% end %>
            <% if hash_day[:rental] %>
              <div class="bg-grey ps-2 py-1 radius-8 mb-2">
                <p class="text-blue mb-0">Rental<%= hash_day[:rental].address %></p>
              </div>
            <% end %>
            <% if hash_day[:places] %>
              <% hash_day[:places].each do |place| %>
                <div class="bg-light-gray ps-2 py-1 radius-8 mb-2">
                  <p class="text-yellow mb-0"><%= place.name %> <<%= place.address %></p>
                </div>
              <% end %>
            <% end %>
          <%= simple_form_for [@trip, Place.new], html: { class: "mt-2"} do |f| %>
            <%= f.input :address, placeholder: "Add a place", label: false %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/trips/map.html.erb
<%= turbo_frame_tag "show_content" do %>
  <div style="width: 100%; height: 100vh;"
        data-controller="map"
        data-map-lodging-markers-value="<%= @lodging_markers.to_json %>"
        data-map-rental-markers-value="<%= @rental_markers.to_json %>"
        data-map-place-markers-value="<%= @place_markers.to_json %>"

        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
<% end %>

app/views/trips/overview.html.erb
<%= turbo_frame_tag :items do %>
  <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview-tab">
    <div class="bg-gray">
      <section class="quick-add-section my-4">
        <h3 class="mb-3 text-blue">Reservations and attachments</h3>
        <ul class="add-list">
          <li>
            <%= link_to new_trip_transit_path(@trip), class: "button-action", data: {bs_toggle: "modal", bs_target: "#new-transit" } do  %>
              <i class="fa-solid fa-train-subway"></i>
              <span>Transport</span>
            <% end %>
          </li>
          <div class="separator"></div>
          <li>
            <%= link_to new_trip_lodging_path(@trip), class: "button-action", data: {bs_toggle: "modal", bs_target: "#new-lodging" } do  %>
              <i class="fa-solid fa-bed"></i>
              <span>Lodging</span>
            <% end %>
          </li>
          <div class="separator"></div>
          <li>
            <%= link_to new_trip_rental_path(@trip), class: "button-action", data: {bs_toggle: "modal", bs_target: "#new-rental" } do  %>
              <i class="fa-solid fa-car"></i>
              <span>Rental</span>
            <% end %>
          </li>
          <div class="separator"></div>
          <li>
            <%= link_to new_trip_place_path(@trip), class: "button-action", data: {bs_toggle: "modal", bs_target: "#new-place" } do  %>
              <i class="fa-solid fa-landmark"></i>
              <span>Activity</span>
            <% end %>
          </li>
          <div class="separator"></div>
          <li>
            <div class="button-action" role="button">
              <i class="fa-solid fa-paperclip"></i>
              <span>Attachment</span>
            </div>
          </li>
        </ul>

        <%= render "shared/new_modal", type: "lodging", item: Lodging.new, trip: @trip, form: "lodgings/form" %>
        <%= render "shared/new_modal", type: "rental", item: Rental.new, trip: @trip, form: "rentals/form" %>
        <%= render "shared/new_modal", type: "transit", item: Transit.new, trip: @trip, form: "transits/form" %>
        <%= render "shared/new_modal", type: "place", item: Place.new, trip: @trip, form: "places/form" %>
      </section>

      <%= render "lodgings/list", trip: @trip %>
      <%= render "transits/list", trip: @trip %>
      <%= render "rentals/list", trip: @trip %>
      <%= render "places/list", trip: @trip %>
    </div>
  </div>
<% end %>

app/views/trips/show.html.erb
<%= turbo_frame_tag "show_content", src: details_trip_path(@trip) %>

<div data-controller="toggle-map">
  <%= link_to map_trip_path(@trip), class: "btn-action action-btn-container map-link", data: { toggle_map_target: "map", "turbo-frame": :"show_content"} do  %>
    <i class="fa-solid fa-map fs-3"></i>
  <% end %>

    <%= link_to details_trip_path(@trip), class: "action-btn-container d-none btn-action", data: { toggle_map_target: "details", "turbo-frame": :"show_content"} do  %>
      <i class="fa-solid fa-list fs-3"></i>
    <% end %>
</div>