config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "pages#profile"
  resources :trips, only: %i[show index new create] do
    resources :lodgings, only: %i[new create]
    resources :transits, only: %i[new create]
    resources :rentals, only: %i[new create]
    resources :places, only: %i[new create]
    resources :expenses, only: %i[index new create]
    resources :items, only: %i[index new create]

    member do
      get :map
      get :details
      get :overview
      get :itinerary
      get :budget
    end
  end
  resources :expenses, only: %i[edit update delete]
  resources :lodgings, only: %i[edit update delete]
  resources :transits, only: %i[edit update delete]
  resources :rentals, only: %i[edit update delete]
  resources :items, only: %i[edit update delete] do
    member do
      get :toggle_packed
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'favicons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'favicons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'favicons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'favicons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'favicons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'favicons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'favicons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'favicons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'favicons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'favicons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'favicons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'favicons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <ul class="d-flex justify-content-between">
      <li class="nav-item active ">
        <%= link_to trips_path, class: "nav-link" do %>
          <i class="fa-solid fa-house"></i>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to "#", class: "nav-link" do %>
          <i class="fa-solid fa-circle-plus"></i>
        <% end %>
      </li>

      <li class="nav-item">
        <%= link_to profile_path, class: "nav-link" do %>
          <i class="fa-solid fa-user"></i>
        <% end %>
      </li>

    </ul>
  </div>
</div>

app/views/shared/_new_modal.html.erb
<div class="modal fade" id="new-<%= type %>" tabindex="-1" aria-labelledby="createItem" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content p-4">
      <% if type == "lodging" %>
        <%= render form, lodging: item, trip: trip %>
      <% elsif type == "rental" %>
        <%= render form, rental: item, trip: trip %>
      <% elsif type == "transit" %>
        <%= render form, transit: item, trip: trip %>
      <% elsif type == "expense" %>
        <%= render form, expense: item, trip: trip %>
      <% else %>
        <%= render form, place: item, trip: trip %>
      <% end %>
    </div>
  </div>
</div>