config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "pages#profile"
  resources :trips, only: %i[show index new create] do
    resources :lodgings, only: %i[new create]
    resources :transits, only: %i[new create]
    resources :rentals, only: %i[new create]
    resources :places, only: %i[new create]
    resources :expenses, only: %i[index new create]
    resources :items, only: %i[index new create]

    member do
      get :map
      get :details
      get :overview
      get :itinerary
      get :budget
    end
  end
  resources :expenses, only: %i[edit update delete]
  resources :lodgings, only: %i[edit update delete]
  resources :transits, only: %i[edit update delete]
  resources :rentals, only: %i[edit update delete]
  resources :items, only: %i[edit update delete] do
    member do
      get :toggle_packed
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :trip

  CATEGORIES = ["Accessories", "Clothing", "Documents", "Electronics", "Food", "Healthcare", "Hiking", "Kitchen", "Recreational", "Sport", "Toiletries", "Work"]

  validates :category, inclusion: { in: CATEGORIES }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[edit update toggle_packed]

  def index
    @trip = Trip.includes(:items).find(params[:trip_id])
    @items = @trip.items
    if params[:sort] == "status"
      @items = @items.group_by(&:packed)
    elsif params[:sort] == "category"
      @items = @items.group_by(&:category)
    end
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @item = Item.new(item_params)
    @item.trip = @trip
    # @category = Category.find_by(name: "Lodging")

    if @item.save!
      redirect_to trip_items_path(@trip)
    else
      render "trips/show"
    end
  end

  def update
    @item.update(item_params)
    redirect_to trip_items_path(@trip)
  end

  def toggle_packed
    @item.update(packed: !@item.packed)
    respond_to do |format|
      format.html { redirect_to trip_path(@item.trip) }
      format.text { render partial: "packed", locals: {item: @item}, formats: [:html] }
    end
  end

  private

  def set_item
    @item = Item.includes(:user, [trip: [trip_users: :user]]).find(params[:id])
  end

  def item_params
    params.require(:item).permit(:user_id, :category, :packed, :name)
  end
end

app/views/items/_edit_form.html.erb
  <%= simple_form_for item, html: { class: ""} do |f| %>
      <%= f.input :name, label: false, placeholder: "Charger, tent, etc" %>
      <%= f.association :user, collection: item.trip.users, include_blank: false , label: false, label_method: :username,  value_method: :id %>
      <%= f.input :category, collection: Item::CATEGORIES, label: false, wrapper_html: {style: "flex-grow: 1; margin-right: 8px"} %>
      <div class="text-center">
        <%= f.submit "save", class: "btn btn-blue ml-3 mb-3" %>
      </div>
    </div>
  <% end %>

app/views/items/_edit_modal.html.erb
<div class="modal fade" id="edit-item-<%= item.id %>" tabindex="-1" aria-labelledby="editItem" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content p-4">
        <%= render "edit_form", item: item %>
    </div>
  </div>
</div>

app/views/items/_form.html.erb
<div class="container new-item bg-white pt-3">
  <p>Add new item</p>
  <%= simple_form_for [trip, item], html: { class: ""} do |f| %>
    <div class="d-flex justify-content-between align-items-center">
      <%= f.input :name, label: false, placeholder: "Charger, tent, etc" %>
      <%= f.association :user, collection: trip.users, include_blank: false , label: false, label_method: :username,  value_method: :id %>
    </div>
    <div class="d-flex justify-content-between align-items-center">
      <%= f.input :category, collection: Item::CATEGORIES, label: false, wrapper_html: {style: "flex-grow: 1; margin-right: 8px"} %>
      <div class="text-center">
        <%= f.submit "+", class: "btn btn-blue btn-small ml-3 mb-3" %>
      </div>
    </div>
  <% end %>


</div>

app/views/items/_list_items.html.erb
  <% items.each do |item| %>
    <%= turbo_frame_tag "item_#{item.id}"  do %>
      <div class="container">
        <li class="p-0 bg-light-gray d-flex px-3 py-2 justify-content-start align-items-center">
          <div class="item-packed me-3" data-controller="toggle-packed" data-toggle-packed-item-value="<%= item.id %>">
            <%= render "packed", item: item %>
          </div>
          <%= link_to edit_item_path(item), class: "edit-link", data: {bs_toggle: "modal", bs_target: "#edit-item-#{item.id}" } do  %>
              <div class="d-flex py-2 justify-content-between align-items-center">
                <div class="item-left">
                  <div class="d-flex align-items-center justify-content-center">
                    <div class="ms-4">
                      <p class="fw-bold mb-0"><%= item.name %></p>
                    </div>
                  </div>
                </div>
                <div class="item-right">
                  <%= cl_image_tag item.user.photo.key, class: "avatar avatar-bordered" %>
                </div>
              </div>
          <% end %>
          <%= render "edit_modal", item: item %>
        </li>
      </div>
    <% end %>
  <% end %>

app/views/items/_new_form.html.erb
<div class="container new-item bg-white py-3">
  <p>Add an item to your checklist</p>
  <%= simple_form_for [trip, item], html: { class: ""} do |f| %>
    <div class="d-flex justify-content-between align-items-center">
      <%= f.input :name, label: false, placeholder: "Charger, tent, etc" %>
      <%= f.association :user, collection: trip.users, include_blank: false , label: false, label_method: :username,  value_method: :id %>
    </div>
    <div class="d-flex justify-content-between align-items-center">
      <%= f.input :category, collection: Item::CATEGORIES, label: false, wrapper_html: {style: "flex-grow: 1; margin-right: 8px"} %>
      <div class="text-center">
        <%= f.submit "+", class: "btn btn-blue btn-small ml-3 mb-3" %>
      </div>
    </div>
  <% end %>
</div>

app/views/items/_packed.html.erb
<% if item.packed %>
  <i class="fa-solid fa-square-check text-yellow"  data-action="click->toggle-packed#toggle"></i>
<% else %>
  <i class="fa-regular fa-square" data-action="click->toggle-packed#toggle"></i>
<% end %>

app/views/items/edit.html.erb
<div class="container new-item bg-white py-3">
  <%= render "edit_form", trip: @trip, item: @item  %>
</div>

app/views/items/index.html.erb
<%= turbo_frame_tag :items do %>

  <div class="">
    <%= render "new_form", trip: @trip, item: Item.new  %>
  </div>

  <ul class="checklist list-section bg-white py-3 mt-3 container">
    <div class="checklist-filter d-flex justify-content-end align-items-center container mb-3">
      <%= link_to "Un/Packed", trip_items_path(sort: "status"), class: "btn" %>
      <%= link_to "Category", trip_items_path(sort: "category"), class: "btn" %>
      <i class="fa-solid fa-filter text-blue"></i>
    </div>
    <% if params[:sort] %>
      <% @items.each do |key, items| %>
        <% if params[:sort] == "status" %>
          <h2 class="ms-3"><%= key ? "Packed" : "Unpacked" %></h2>
        <% else %>
          <h2 class="ms-3"><%= key %></h2>
        <% end %>
        <%= render "list_items", items: items %>
      <% end %>
    <% else %>
      <%= render "list_items", items: @items %>
    <% end %>
  </ul>
<% end %>