config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "pages#profile"
  resources :trips, only: %i[show index new create] do
    resources :lodgings, only: %i[new create]
    resources :transits, only: %i[new create]
    resources :rentals, only: %i[new create]
    resources :places, only: %i[new create]
    resources :expenses, only: %i[index new create]
    resources :items, only: %i[index new create]

    member do
      get :map
      get :details
      get :overview
      get :itinerary
      get :budget
    end
  end
  resources :expenses, only: %i[edit update delete]
  resources :lodgings, only: %i[edit update delete]
  resources :transits, only: %i[edit update delete]
  resources :rentals, only: %i[edit update delete]
  resources :items, only: %i[edit update delete] do
    member do
      get :toggle_packed
    end
  end
end

app/models/lodging.rb
class Lodging < ApplicationRecord
  belongs_to :trip
  has_many_attached :attachments

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/lodgings_controller.rb
class LodgingsController < ApplicationController
  before_action :set_lodging, only: %i[edit update]

  def new
    @trip = Trip.find(params[:trip_id])
    @lodging = Lodging.new
  end

  def update
    @trip = @lodging.trip
    @lodging.update(lodging_params)
    redirect_to trip_path(@trip)
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @lodging = Lodging.new(lodging_params)
    @lodging.trip = @trip
    @category = Category.find_by(name: "Lodging")

    if @lodging.save
      Expense.create(
        trip: @trip,
        user: current_user,
        lodging: @lodging,
        category: @category,
        comment: @lodging.name,
        date: Date.today
      )
      redirect_to trip_path(@trip)
    else
      render "trips/show"
    end
  end

  private

  def set_lodging
    @lodging = Lodging.find(params[:id])
  end

  def lodging_params
    params.require(:lodging).permit(:name,
                                    :link,
                                    :paid,
                                    :start_time,
                                    :end_time,
                                    :address,
                                    :price_cents,
                                    :price_per_night_cents,
                                    attachments: [])
  end
end

app/views/lodgings/_form.html.erb
<div class="container py-3 px-3">
  <% unless lodging.persisted? %>
    <h2 class="mb-2">Add a new lodging</h2>
  <% end %>
  <%= simple_form_for [trip, lodging], data: { controller: 'flatpickr' } do |f| %>
    <%= f.input :name, label: false, placeholder: "name" %>
    <%= f.input :start_time, label: false,  placeholder: "Date of arrival", as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
    <%= f.input :end_time, label: false,  placeholder: "Date of departure", as: :string,  type: :text, input_html: { data: { flatpickr_target: "endTime" } } %>
    <%= f.input :link, label: false, placeholder: "url" %>
    <%= f.input :address, label: false, placeholder: "address" %>
    <%= f.input :price_cents, label: false, placeholder: "price in total" %>
    <%= f.input :paid, label: false, placeholder: "paid" %>
    <%= f.input :attachments, label: false, placeholder: "paid", as: :file, input_html: { multiple: true } %>
    <div class="text-center">
      <%= f.submit "Add", class: "btn btn-blue btn-large" %>
    </div>
  <% end %>
</div>

app/views/lodgings/_list.html.erb
<section class="list-section mb-4" data-controller="reveal" data-reveal-hidden-class="d-none">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <button class="btn d-flex justify-content-start align-items-center" data-action="click->reveal#toggle" >
      <i class="fa-solid fa-caret-down me-3 text-blue"></i>
      <h2 class="mb-0 text-blue">Accomodations</h3>
    </button>
    <%= link_to new_trip_lodging_path(@trip), class: "button-action", data: {bs_toggle: "modal", bs_target: "#new-lodging" } do  %>
      <span class="text-yellow fs-4"><i class="fa-solid fa-plus"></i></span>
    <% end %>
  </div>
  <div class="list-rentals d-none" data-reveal-target="item" >
    <% if trip.lodgings.empty? %>
      <p class="text-gray font-italic mb-0">No lodgings yet</p>
    <% else %>
      <ul class="lodging-list">
        <% trip.lodgings.each do |lodging| %>
          <%= turbo_frame_tag "lodging_#{lodging.id}"  do %>
            <li class="bg-gray lodging">
              <%= link_to edit_lodging_path(lodging) do  %>
                <h3 class="text-blue fw-bolder"><%= lodging.name %></h3>
                <div class="d-flex justify-content-between align-items-end">
                  <div>
                    <p class="text-small mb-1"><%= lodging.address %></p>
                    <p class="mb-0"><%= lodging.start_time.strftime("%a, %d %b") %> - <%= lodging.end_time.strftime("%a, %d %b") %></p>
                  </div>
                  <p class="mb-0"><i class="fa-solid fa-circle-chevron-down"></i></p>
                </div>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  </div>
</section>

app/views/lodgings/edit.html.erb
<%= turbo_frame_tag "lodging_#{@lodging.id}" do %>
  <div class="bg-gray mb-3 radius-8">
    <%= render "form", trip: @trip, lodging: @lodging  %>
  </div>
<% end %>

app/views/lodgings/new.html.erb
<%= turbo_frame_tag "lodgings_turbo_frame" do %>
  <%= render "form", trip: @trip, lodging: @lodging  %>
<% end %>